pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
    }
}

rootProject.name = "Aflami"
include(":app")
include(":designsystem")
include(":logger")
include(":domain")
include(":domain:user")
include(":domain:guessGame")
include(":domain:media")
include(":repository")
include(":repository:lists")
include(":repository:guessGame")
include(":repository:movie")
include(":repository:tvShows")
include(":repository:media")
include(":repository:user")
include(":datasource")
include(":datasource:remote")
include(":datasource:remote:user")
include(":datasource:remote:lists")
include(":datasource:remote:tvShow")
include(":datasource:remote:categories")
include(":datasource:remote:user")
include(":datasource:remote:media")
include(":datasource:remote:search")
include(":datasource:remote:movie")
include(":datasource:local")
include(":datasource:local:movie")
include(":datasource:local:tvShow")
include(":datasource:local:lists")
include(":datasource:local:guessGame")
include(":datasource:local:categories")
include(":datasource:local:media")
include(":datasource:local:user")
include(":feature")
include(":feature:onboarding")
include(":feature:onboarding:onboardingApi")
include(":feature:authentication")
include(":feature:authentication:authenticationApi")
include(":feature:home")
include(":feature:home:homeApi")
include(":feature:onboarding:onboardingUi")
include(":feature:authentication:authenticationUi")
include(":feature:home:homeUi")
include(":feature:profile")
include(":feature:profile:profileApi")
include(":feature:profile:profileUi")
include(":feature:search")
include(":feature:search:searchApi")
include(":feature:search:searchUi")
include(":feature:mediaDetails")
include(":feature:mediaDetails:mediaDetailsApi")
include(":feature:mediaDetails:mediaDetailsUi")
include(":feature:guessGame")
include(":feature:guessGame:guessGameApi")
include(":feature:guessGame:guessGameUi")
include(":feature:categories")
include(":feature:categories:categoriesApi")
include(":feature:categories:categoriesUi")
include(":feature:lists")
include(":feature:lists:listsApi")
include(":feature:lists:listsUi")
include(":feature:bottomNavBar")
include(":datasource:local:search")
include(":safeimageviewer")
include(":datasource:remote:movie")
include(":datasource:remote:home")
include(":datasource:local:home")
include(":datasource:remote:authentication")
include(":repository:authentication")
include(":datasource:local:authentication")
include(":domain:lists")
include(":feature:bottomNavBar:bottomNavBarUI")
include(":feature:bottomNavBar:bottomNavBarApi")
