package com.repository.search.util

import com.repository.search.entity.CountryEntity

object Util {

    val countryList = listOf(
        CountryEntity("AD", "Andorra", "أندورا"),
        CountryEntity("AE", "United Arab Emirates", "الإمارات العربية المتحدة"),
        CountryEntity("AF", "Afghanistan", "أفغانستان"),
        CountryEntity("AG", "Antigua and Barbuda", "أنتيغوا وباربودا"),
        CountryEntity("AI", "Anguilla", "أنغويلا"),
        CountryEntity("AL", "Albania", "ألبانيا"),
        CountryEntity("AM", "Armenia", "أرمينيا"),
        CountryEntity("AO", "Angola", "أنغولا"),
        CountryEntity("AQ", "Antarctica", "أنتاركتيكا"),
        CountryEntity("AR", "Argentina", "الأرجنتين"),
        CountryEntity("AS", "American Samoa", "ساموا الأمريكية"),
        CountryEntity("AT", "Austria", "النمسا"),
        CountryEntity("AU", "Australia", "أستراليا"),
        CountryEntity("AW", "Aruba", "أروبا"),
        CountryEntity("AX", "Åland Islands", "جزر أولاند"),
        CountryEntity("AZ", "Azerbaijan", "أذربيجان"),
        CountryEntity("BA", "Bosnia and Herzegovina", "البوسنة والهرسك"),
        CountryEntity("BB", "Barbados", "باربادوس"),
        CountryEntity("BD", "Bangladesh", "بنغلاديش"),
        CountryEntity("BE", "Belgium", "بلجيكا"),
        CountryEntity("BF", "Burkina Faso", "بوركينا فاسو"),
        CountryEntity("BG", "Bulgaria", "بلغاريا"),
        CountryEntity("BH", "Bahrain", "البحرين"),
        CountryEntity("BI", "Burundi", "بوروندي"),
        CountryEntity("BJ", "Benin", "بنين"),
        CountryEntity("BL", "Saint Barthélemy", "سان بارتيلمي"),
        CountryEntity("BM", "Bermuda", "برمودا"),
        CountryEntity("BN", "Brunei Darussalam", "بروناي"),
        CountryEntity("BO", "Bolivia (Plurinational State of)", "بوليفيا"),
        CountryEntity("BQ", "Bonaire, Sint Eustatius and Saba", "بونير وسينت أوستاتيوس وسابا"),
        CountryEntity("BR", "Brazil", "البرازيل"),
        CountryEntity("BS", "Bahamas", "باهاماس"),
        CountryEntity("BT", "Bhutan", "بوتان"),
        CountryEntity("BV", "Bouvet Island", "جزيرة بوفيه"),
        CountryEntity("BW", "Botswana", "بوتسوانا"),
        CountryEntity("BY", "Belarus", "بيلاروسيا"),
        CountryEntity("BZ", "Belize", "بليز"),
        CountryEntity("CA", "Canada", "كندا"),
        CountryEntity("CC", "Cocos (Keeling) Islands", "جزر كوكوس"),
        CountryEntity("CD", "Congo (Democratic Republic of the)", "جمهورية الكونغو الديمقراطية"),
        CountryEntity("CF", "Central African Republic", "جمهورية أفريقيا الوسطى"),
        CountryEntity("CG", "Congo", "الكونغو"),
        CountryEntity("CH", "Switzerland", "سويسرا"),
        CountryEntity("CI", "Côte d'Ivoire", "ساحل العاج"),
        CountryEntity("CK", "Cook Islands", "جزر كوك"),
        CountryEntity("CL", "Chile", "تشيلي"),
        CountryEntity("CM", "Cameroon", "الكاميرون"),
        CountryEntity("CN", "China", "الصين"),
        CountryEntity("CO", "Colombia", "كولومبيا"),
        CountryEntity("CR", "Costa Rica", "كوستاريكا"),
        CountryEntity("CU", "Cuba", "كوبا"),
        CountryEntity("CV", "Cabo Verde", "الرأس الأخضر"),
        CountryEntity("CW", "Curaçao", "كوراساو"),
        CountryEntity("CX", "Christmas Island", "جزيرة كريسماس"),
        CountryEntity("CY", "Cyprus", "قبرص"),
        CountryEntity("CZ", "Czechia", "التشيك"),
        CountryEntity("DE", "Germany", "ألمانيا"),
        CountryEntity("DJ", "Djibouti", "جيبوتي"),
        CountryEntity("DK", "Denmark", "الدنمارك"),
        CountryEntity("DM", "Dominica", "دومينيكا"),
        CountryEntity("DO", "Dominican Republic", "جمهورية الدومينيكان"),
        CountryEntity("DZ", "Algeria", "الجزائر"),
        CountryEntity("EC", "Ecuador", "الإكوادور"),
        CountryEntity("EE", "Estonia", "إستونيا"),
        CountryEntity("EG", "Egypt", "مصر"),
        CountryEntity("EH", "Western Sahara", "الصحراء الغربية"),
        CountryEntity("ER", "Eritrea", "إريتريا"),
        CountryEntity("ES", "Spain", "إسبانيا"),
        CountryEntity("ET", "Ethiopia", "إثيوبيا"),
        CountryEntity("FI", "Finland", "فنلندا"),
        CountryEntity("FJ", "Fiji", "فيجي"),
        CountryEntity("FK", "Falkland Islands (Malvinas)", "جزر فوكلاند"),
        CountryEntity("FM", "Micronesia (Federated States of)", "ميكرونيسيا"),
        CountryEntity("FO", "Faroe Islands", "جزر فارو"),
        CountryEntity("FR", "France", "فرنسا"),
        CountryEntity("GA", "Gabon", "الغابون"),
        CountryEntity("GB", "United Kingdom of Great Britain and Northern Ireland", "المملكة المتحدة"),
        CountryEntity("GD", "Grenada", "غرينادا"),
        CountryEntity("GE", "Georgia", "جورجيا"),
        CountryEntity("GF", "French Guiana", "غويانا الفرنسية"),
        CountryEntity("GG", "Guernsey", "غيرنزي"),
        CountryEntity("GH", "Ghana", "غانا"),
        CountryEntity("GI", "Gibraltar", "جبل طارق"),
        CountryEntity("GL", "Greenland", "غرينلاند"),
        CountryEntity("GM", "Gambia", "غامبيا"),
        CountryEntity("GN", "Guinea", "غينيا"),
        CountryEntity("GP", "Guadeloupe", "غوادلوب"),
        CountryEntity("GQ", "Equatorial Guinea", "غينيا الاستوائية"),
        CountryEntity("GR", "Greece", "اليونان"),
        CountryEntity("GS", "South Georgia and the South Sandwich Islands", "جورجيا الجنوبية وجزر ساندويتش الجنوبية"),
        CountryEntity("GT", "Guatemala", "غواتيمالا"),
        CountryEntity("GU", "Guam", "غوام"),
        CountryEntity("GW", "Guinea-Bissau", "غينيا بيساو"),
        CountryEntity("GY", "Guyana", "غيانا"),
        CountryEntity("HK", "Hong Kong", "هونغ كونغ"),
        CountryEntity("HM", "Heard Island and McDonald Islands", "جزيرة هيرد وجزر ماكدونالد"),
        CountryEntity("HN", "Honduras", "هندوراس"),
        CountryEntity("HR", "Croatia", "كرواتيا"),
        CountryEntity("HT", "Haiti", "هايتي"),
        CountryEntity("HU", "Hungary", "المجر"),
        CountryEntity("ID", "Indonesia", "إندونيسيا"),
        CountryEntity("IE", "Ireland", "أيرلندا"),
        CountryEntity("IM", "Isle of Man", "جزيرة مان"),
        CountryEntity("IN", "India", "الهند"),
        CountryEntity("IO", "British Indian Ocean Territory", "إقليم المحيط الهندي البريطاني"),
        CountryEntity("IQ", "Iraq", "العراق"),
        CountryEntity("IR", "Iran (Islamic Republic of)", "إيران"),
        CountryEntity("IS", "Iceland", "آيسلندا"),
        CountryEntity("IT", "Italy", "إيطاليا"),
        CountryEntity("JE", "Jersey", "جيرزي"),
        CountryEntity("JM", "Jamaica", "جامايكا"),
        CountryEntity("JO", "Jordan", "الأردن"),
        CountryEntity("JP", "Japan", "اليابان"),
        CountryEntity("KE", "Kenya", "كينيا"),
        CountryEntity("KG", "Kyrgyzstan", "قيرغيزستان"),
        CountryEntity("KH", "Cambodia", "كمبوديا"),
        CountryEntity("KI", "Kiribati", "كيريباتي"),
        CountryEntity("KM", "Comoros", "جزر القمر"),
        CountryEntity("KN", "Saint Kitts and Nevis", "سانت كيتس ونيفيس"),
        CountryEntity("KP", "Korea (Democratic People's Republic of)", "كوريا الشمالية"),
        CountryEntity("KR", "Korea (Republic of)", "كوريا الجنوبية"),
        CountryEntity("KW", "Kuwait", "الكويت"),
        CountryEntity("KY", "Cayman Islands", "جزر كايمان"),
        CountryEntity("KZ", "Kazakhstan", "كازاخستان"),
        CountryEntity("LA", "Lao People's Democratic Republic", "لاوس"),
        CountryEntity("LB", "Lebanon", "لبنان"),
        CountryEntity("LC", "Saint Lucia", "سانت لوسيا"),
        CountryEntity("LI", "Liechtenstein", "ليختنشتاين"),
        CountryEntity("LK", "Sri Lanka", "سريلانكا"),
        CountryEntity("LR", "Liberia", "ليبيريا"),
        CountryEntity("LS", "Lesotho", "ليسوتو"),
        CountryEntity("LT", "Lithuania", "ليتوانيا"),
        CountryEntity("LU", "Luxembourg", "لوكسمبورغ"),
        CountryEntity("LV", "Latvia", "لاتفيا"),
        CountryEntity("LY", "Libya", "ليبيا"),
        CountryEntity("MA", "Morocco", "المغرب"),
        CountryEntity("MC", "Monaco", "موناكو"),
        CountryEntity("MD", "Moldova (Republic of)", "مولدوفا"),
        CountryEntity("ME", "Montenegro", "الجبل الأسود"),
        CountryEntity("MF", "Saint Martin (French part)", "سانت مارتن"),
        CountryEntity("MG", "Madagascar", "مدغشقر"),
        CountryEntity("MH", "Marshall Islands", "جزر مارشال"),
        CountryEntity("MK", "North Macedonia", "مقدونيا الشمالية"),
        CountryEntity("ML", "Mali", "مالي"),
        CountryEntity("MM", "Myanmar", "ميانمار"),
        CountryEntity("MN", "Mongolia", "منغوليا"),
        CountryEntity("MO", "Macao", "ماكاو"),
        CountryEntity("MP", "Northern Mariana Islands", "جزر ماريانا الشمالية"),
        CountryEntity("MQ", "Martinique", "مارتينيك"),
        CountryEntity("MR", "Mauritania", "موريتانيا"),
        CountryEntity("MS", "Montserrat", "مونتسيرات"),
        CountryEntity("MT", "Malta", "مالطا"),
        CountryEntity("MU", "Mauritius", "موريشيوس"),
        CountryEntity("MV", "Maldives", "جزر المالديف"),
        CountryEntity("MW", "Malawi", "مالاوي"),
        CountryEntity("MX", "Mexico", "المكسيك"),
        CountryEntity("MY", "Malaysia", "ماليزيا"),
        CountryEntity("MZ", "Mozambique", "موزمبيق"),
        CountryEntity("NA", "Namibia", "ناميبيا"),
        CountryEntity("NC", "New Caledonia", "كاليدونيا الجديدة"),
        CountryEntity("NE", "Niger", "النيجر"),
        CountryEntity("NF", "Norfolk Island", "جزيرة نورفولك"),
        CountryEntity("NG", "Nigeria", "نيجيريا"),
        CountryEntity("NI", "Nicaragua", "نيكاراغوا"),
        CountryEntity("NL", "Netherlands", "هولندا"),
        CountryEntity("NO", "Norway", "النرويج"),
        CountryEntity("NP", "Nepal", "نيبال"),
        CountryEntity("NR", "Nauru", "ناورو"),
        CountryEntity("NU", "Niue", "نيوي"),
        CountryEntity("NZ", "New Zealand", "نيوزيلندا"),
        CountryEntity("OM", "Oman", "عُمان"),
        CountryEntity("PA", "Panama", "بنما"),
        CountryEntity("PE", "Peru", "بيرو"),
        CountryEntity("PF", "French Polynesia", "بولينيزيا الفرنسية"),
        CountryEntity("PG", "Papua New Guinea", "بابوا غينيا الجديدة"),
        CountryEntity("PH", "Philippines", "الفلبين"),
        CountryEntity("PK", "Pakistan", "باكستان"),
        CountryEntity("PL", "Poland", "بولندا"),
        CountryEntity("PM", "Saint Pierre and Miquelon", "سان بيير وميكلون"),
        CountryEntity("PN", "Pitcairn", "جزر بيتكيرن"),
        CountryEntity("PR", "Puerto Rico", "بورتوريكو"),
        CountryEntity("PS", "Palestine, State of", "فلسطين"),
        CountryEntity("PT", "Portugal", "البرتغال"),
        CountryEntity("PW", "Palau", "بالاو"),
        CountryEntity("PY", "Paraguay", "باراغواي"),
        CountryEntity("QA", "Qatar", "قطر"),
        CountryEntity("RE", "Réunion", "ريونيون"),
        CountryEntity("RO", "Romania", "رومانيا"),
        CountryEntity("RS", "Serbia", "صربيا"),
        CountryEntity("RU", "Russian Federation", "روسيا"),
        CountryEntity("RW", "Rwanda", "رواندا"),
        CountryEntity("SA", "Saudi Arabia", "السعودية"),
        CountryEntity("SB", "Solomon Islands", "جزر سليمان"),
        CountryEntity("SC", "Seychelles", "سيشل"),
        CountryEntity("SD", "Sudan", "السودان"),
        CountryEntity("SE", "Sweden", "السويد"),
        CountryEntity("SG", "Singapore", "سنغافورة"),
        CountryEntity("SH", "Saint Helena, Ascension and Tristan da Cunha", "سانت هيلينا وأسينشين وتريستان دا كونا"),
        CountryEntity("SI", "Slovenia", "سلوفينيا"),
        CountryEntity("SJ", "Svalbard and Jan Mayen", "سفالبارد ويان ماين"),
        CountryEntity("SK", "Slovakia", "سلوفاكيا"),
        CountryEntity("SL", "Sierra Leone", "سيراليون"),
        CountryEntity("SM", "San Marino", "سان مارينو"),
        CountryEntity("SN", "Senegal", "السنغال"),
        CountryEntity("SO", "Somalia", "الصومال"),
        CountryEntity("SR", "Suriname", "سورينام"),
        CountryEntity("SS", "South Sudan", "جنوب السودان"),
        CountryEntity("ST", "Sao Tome and Principe", "ساو تومي وبرينسيب"),
        CountryEntity("SV", "El Salvador", "السلفادور"),
        CountryEntity("SX", "Sint Maarten (Dutch part)", "سينت مارتن"),
        CountryEntity("SY", "Syrian Arab Republic", "سوريا"),
        CountryEntity("SZ", "Eswatini", "إسواتيني"),
        CountryEntity("TC", "Turks and Caicos Islands", "جزر توركس وكايكوس"),
        CountryEntity("TD", "Chad", "تشاد"),
        CountryEntity("TF", "French Southern Territories", "الأراضي الجنوبية الفرنسية"),
        CountryEntity("TG", "Togo", "توغو"),
        CountryEntity("TH", "Thailand", "تايلاند"),
        CountryEntity("TJ", "Tajikistan", "طاجيكستان"),
        CountryEntity("TK", "Tokelau", "توكيلاو"),
        CountryEntity("TL", "Timor-Leste", "تيمور الشرقية"),
        CountryEntity("TM", "Turkmenistan", "تركمانستان"),
        CountryEntity("TN", "Tunisia", "تونس"),
        CountryEntity("TO", "Tonga", "تونغا"),
        CountryEntity("TR", "Turkey", "تركيا"),
        CountryEntity("TT", "Trinidad and Tobago", "ترينيداد وتوباغو"),
        CountryEntity("TV", "Tuvalu", "توفالو"),
        CountryEntity("TW", "Taiwan (Province of China)", "تايوان"),
        CountryEntity("TZ", "Tanzania, United Republic of", "تنزانيا"),
        CountryEntity("UA", "Ukraine", "أوكرانيا"),
        CountryEntity("UG", "Uganda", "أوغندا"),
        CountryEntity("UM", "United States Minor Outlying Islands", "جزر الولايات المتحدة الصغيرة النائية"),
        CountryEntity("US", "United States of America", "الولايات المتحدة"),
        CountryEntity("UY", "Uruguay", "أوروغواي"),
        CountryEntity("UZ", "Uzbekistan", "أوزبكستان"),
        CountryEntity("VA", "Holy See", "الفاتيكان"),
        CountryEntity("VC", "Saint Vincent and the Grenadines", "سانت فنسنت والغرينادين"),
        CountryEntity("VE", "Venezuela (Bolivarian Republic of)", "فنزويلا"),
        CountryEntity("VG", "Virgin Islands (British)", "جزر العذراء البريطانية"),
        CountryEntity("VI", "Virgin Islands (U.S.)", "جزر العذراء الأمريكية"),
        CountryEntity("VN", "Viet Nam", "فيتنام"),
        CountryEntity("VU", "Vanuatu", "فانواتو"),
        CountryEntity("WF", "Wallis and Futuna", "واليس وفوتونا"),
        CountryEntity("WS", "Samoa", "ساموا"),
        CountryEntity("YE", "Yemen", "اليمن"),
        CountryEntity("YT", "Mayotte", "مايوت"),
        CountryEntity("ZA", "South Africa", "جنوب أفريقيا"),
        CountryEntity("ZM", "Zambia", "زامبيا"),
        CountryEntity("ZW", "Zimbabwe", "زيمبابوي")
    )
}