[versions]
agp = "8.10.1"
android-youtube-player = "12.1.2"
coilComposeVersion = "2.4.0"
datastorePreferences = "1.1.7"
firebaseBom = "33.16.0"
firebaseCrashlytics = "3.0.6"
coil = "2.7.0"
hiltAndroid = "2.57"
hiltAndroidCompiler = "2.57"
hiltNavigationCompose = "1.2.0"
junitJupiterApi = "5.13.4"
junitJupiterEngine = "5.13.4"
junitJupiterParams = "5.13.4"
junitPlatformLauncher = "1.13.4"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlinxCoroutinesCore = "1.10.2"
kotlinxDatetime = "0.7.0"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.07.00"
appcompat = "1.7.1"
material = "1.12.0"
jetbrainsKotlinJvm = "2.2.0"
googleFirebaseAppdistribution = "5.1.1"
googleGmsGoogleServices = "4.4.3"
mockk = "1.14.5"
pagingRuntime = "3.3.6"
startupRuntime = "1.2.0"
tensorflowLite = "2.13.0"
tensorflowLiteSupport = "0.4.4"
tensorflowLiteMetadata = "0.1.0"
lifecycleViewmodelCompose = "2.9.2"
roomKtx = "2.7.2"
roomRuntime = "2.7.2"
roomTesting = "2.7.2"
roomCompiler = "2.7.2"
ksp = "2.2.0-2.0.2"
serializationJson = "1.9.0"
navigationCompose = "2.9.3"
truth = "1.4.4"
junitJupiter = "5.13.4"
coroutines-test = "1.10.2"
splashscreen = "1.0.1"
kover = "0.9.1"
roomCommonJvm = "2.7.2"
webkit = "1.14.0"
workKtx = "2.10.3"
loggingInterceptor = "5.1.0"
okhttp = "5.1.0"
retrofit = "3.0.0"
shaded = "0.2.1-alpha"
hiltCommon = "1.2.0"
datastoreCoreAndroid = "1.1.7"
foundation = "1.8.3"
accompanistPagerVersion = "0.36.0"
firebasePerf = "1.4.2"
junitJupiterVersion = "5.8.1"

[libraries]
# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingRuntime" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "pagingRuntime" }
androidx-startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startupRuntime" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

# YouTube Player
android-youtube-player = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "android-youtube-player" }

# Kotlin
coil-compose-v240 = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }

# Material Design
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Navigation
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Room
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "roomTesting" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }

# Work Manager
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workKtx" }

# Retrofit
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit_converter = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }

# Blur
sifr-shaded = { group = "com.github.mohamedd-hassan", name = "Shaded", version.ref = "shaded" }

# Shimmer
shimmer = {group = "com.valentinilk.shimmer", name = "compose-shimmer", version = "1.3.1" }

#Splash
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }

#tensorflow
tensorflow-lite = { group = "org.tensorflow", name = "tensorflow-lite", version.ref = "tensorflowLite" }
tensorflow-lite-support = { group = "org.tensorflow", name = "tensorflow-lite-support", version.ref = "tensorflowLiteSupport" }
tensorflow-lite-metadata = { group = "org.tensorflow", name = "tensorflow-lite-metadata", version.ref = "tensorflowLiteMetadata" }

#hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version = "1.2.0" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltCommon" }

#firebase
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf" }

#testing
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiterApi" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiterEngine" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitJupiterParams" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatformLauncher" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5" }

#coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

#Accompanist
accompanist-pager-v0340 = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanistPagerVersion" }

#datastore
androidx-datastore-core-android = { group = "androidx.datastore", name = "datastore-core-android", version.ref = "datastoreCoreAndroid" }
jupiter-junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiterVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
google-firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "googleFirebaseAppdistribution" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }

[bundles]

android = [
    "androidx-core-ktx"
]

compose = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "material",
    "androidx-activity-compose",
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling",
    "androidx-ui-tooling-preview",
    "androidx-lifecycle-runtime-ktx",
    "androidx-ui-test-manifest",
    "androidx-foundation",
]

navigation = [
    "navigation-compose",
    "androidx-hilt-navigation-compose"
]

test = [
    "junit",
    "junit-jupiter-engine",
    "junit-jupiter-api",
    "mockk",
    "kotlinx-coroutines-test",
    "truth",
    "kotlin-test",
    "junit-jupiter-params",
    "junit-platform-launcher",
    "androidx-room-testing"
]

hilt = [
    "hilt-android",
    "hilt-work",
    "androidx-hilt-navigation-compose",
]

retrofit = [
    "retrofit",
    "retrofit_converter",
    "logging-interceptor",
    "okhttp"
]

room = [
    "androidx-room-runtime",
    "androidx-room-testing"
]

datetime = [
    "kotlinx-datetime"
]

workManager = [
    "work-runtime-ktx",
    "androidx-startup-runtime"
]

serialization = [
    "kotlinx-serialization-json"
]

paging = [
    "androidx-paging-runtime",
    "androidx-paging-compose"
]

coil = [
    "coil-compose"
]

datastore = [
    "androidx-datastore-preferences",
    "androidx-datastore-core-android"
]

blur = [
    "sifr-shaded"
]

shimmer = [
    "shimmer"
]

webview = [
    "androidx-webkit"
]

pager = [
    "accompanist-pager-v0340",
]

firebase = [
    "firebase-analytics",
    "firebase-crashlytics",
    "firebase-perf"
]

tensorflow = [
    "tensorflow-lite",
    "tensorflow-lite-support",
    "tensorflow-lite-metadata"
]