package com.domain.search.useCases

import com.domain.search.model.Media
import com.domain.search.model.MediaType
import com.domain.search.model.SearchHistoryModel
import kotlinx.datetime.LocalDate

class TemporaryFakeData {

    companion object {
        val mediaList = listOf<Media>(
            Media(
                id = 1,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 1",
                type = MediaType.MOVIE,
                categories = listOf("Action", "Adventure"),
                yearOfRelease = LocalDate(2022, 5, 20),
                rating = 8.5,
            ),
            Media(
                id = 2,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 1",
                type = MediaType.TVSHOW,
                categories = listOf("Drama", "Thriller"),
                yearOfRelease = LocalDate(2021, 3, 15),
                rating = 9.0,
            ),
            Media(
                id = 3,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 2",
                type = MediaType.MOVIE,
                categories = listOf("Comedy", "Romance"),
                yearOfRelease = LocalDate(2020, 7, 10),
                rating = 7.5,
            ),
            Media(
                id = 4,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 2",
                type = MediaType.TVSHOW,
                categories = listOf("Sci-Fi", "Fantasy"),
                yearOfRelease = LocalDate(2019, 11, 5),
                rating = 8.0,
            ),
            Media(
                id = 5,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 3",
                type = MediaType.MOVIE,
                categories = listOf("Horror", "Mystery"),
                yearOfRelease = LocalDate(2018, 2, 28),
                rating = 6.5,
            ),
            Media(
                id = 6,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 4",
                type = MediaType.MOVIE,
                categories = listOf("Action", "Comedy"),
                yearOfRelease = LocalDate(2017, 6, 12),
                rating = 7.0,
            ),
            Media(
                id = 7,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 3",
                type = MediaType.TVSHOW,
                categories = listOf("Drama", "Mystery"),
                yearOfRelease = LocalDate(2016, 9, 18),
                rating = 8.2,
            ),
            Media(
                id = 8,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 5",
                type = MediaType.MOVIE,
                categories = listOf("Adventure", "Fantasy"),
                yearOfRelease = LocalDate(2015, 4, 22),
                rating = 7.8,
            ),
            Media(
                id = 9,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 4",
                type = MediaType.TVSHOW,
                categories = listOf("Thriller", "Horror"),
                yearOfRelease = LocalDate(2014, 8, 30),
                rating = 8.7,
            ),
            Media(
                id = 10,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 6",
                type = MediaType.MOVIE,
                categories = listOf("Romance", "Drama"),
                yearOfRelease = LocalDate(2013, 12, 5),
                rating = 6.9,
            ),
            Media(
                id = 11,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 5",
                type = MediaType.TVSHOW,
                categories = listOf("Comedy", "Action"),
                yearOfRelease = LocalDate(2012, 3, 14),
                rating = 7.3,
            ),
            Media(
                id = 12,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 7",
                type = MediaType.MOVIE,
                categories = listOf("Sci-Fi", "Adventure"),
                yearOfRelease = LocalDate(2011, 7, 19),
                rating = 8.1,
            ),
            Media(
                id = 13,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 6",
                type = MediaType.TVSHOW,
                categories = listOf("Fantasy", "Drama"),
                yearOfRelease = LocalDate(2010, 11, 23),
                rating = 7.6,
            ),
            Media(
                id = 14,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 8",
                type = MediaType.MOVIE,
                categories = listOf("Action", "Thriller"),
                yearOfRelease = LocalDate(2009, 2, 17),
                rating = 7.4,
            ),
            Media(
                id = 15,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 7",
                type = MediaType.TVSHOW,
                categories = listOf("Mystery", "Horror"),
                yearOfRelease = LocalDate(2008, 5, 29),
                rating = 8.3,
            ),
            Media(
                id = 16,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 9",
                type = MediaType.MOVIE,
                categories = listOf("Comedy", "Romance"),
                yearOfRelease = LocalDate(2007, 8, 11),
                rating = 6.8,
            ),
            Media(
                id = 17,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 8",
                type = MediaType.TVSHOW,
                categories = listOf("Drama", "Action"),
                yearOfRelease = LocalDate(2006, 10, 21),
                rating = 7.9,
            ),
            Media(
                id = 18,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 10",
                type = MediaType.MOVIE,
                categories = listOf("Adventure", "Fantasy"),
                yearOfRelease = LocalDate(2005, 1, 13),
                rating = 7.2,
            ),
            Media(
                id = 19,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 9",
                type = MediaType.TVSHOW,
                categories = listOf("Thriller", "Comedy"),
                yearOfRelease = LocalDate(2004, 4, 27),
                rating = 8.4,
            ),
            Media(
                id = 20,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 11",
                type = MediaType.MOVIE,
                categories = listOf("Horror", "Mystery"),
                yearOfRelease = LocalDate(2003, 6, 9),
                rating = 6.7,
            ),
            Media(
                id = 21,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 10",
                type = MediaType.TVSHOW,
                categories = listOf("Action", "Adventure"),
                yearOfRelease = LocalDate(2002, 9, 15),
                rating = 7.5,
            ),
            Media(
                id = 22,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 12",
                type = MediaType.MOVIE,
                categories = listOf("Drama", "Romance"),
                yearOfRelease = LocalDate(2001, 12, 3),
                rating = 7.1,
            ),
            Media(
                id = 23,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 11",
                type = MediaType.TVSHOW,
                categories = listOf("Comedy", "Fantasy"),
                yearOfRelease = LocalDate(2000, 2, 20),
                rating = 8.0,
            ),
            Media(
                id = 24,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 13",
                type = MediaType.MOVIE,
                categories = listOf("Action", "Thriller"),
                yearOfRelease = LocalDate(1999, 5, 8),
                rating = 7.6,
            ),
            Media(
                id = 25,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 12",
                type = MediaType.TVSHOW,
                categories = listOf("Drama", "Mystery"),
                yearOfRelease = LocalDate(1998, 7, 19),
                rating = 8.1,
            ),
            Media(
                id = 26,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 14",
                type = MediaType.MOVIE,
                categories = listOf("Comedy", "Romance"),
                yearOfRelease = LocalDate(1997, 10, 2),
                rating = 6.9,
            ),
            Media(
                id = 27,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 13",
                type = MediaType.TVSHOW,
                categories = listOf("Action", "Adventure"),
                yearOfRelease = LocalDate(1996, 1, 25),
                rating = 7.7,
            ),
            Media(
                id = 28,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 15",
                type = MediaType.MOVIE,
                categories = listOf("Drama", "Thriller"),
                yearOfRelease = LocalDate(1995, 3, 14),
                rating = 7.3,
            ),
            Media(
                id = 29,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 14",
                type = MediaType.TVSHOW,
                categories = listOf("Comedy", "Fantasy"),
                yearOfRelease = LocalDate(1994, 6, 7),
                rating = 8.2,
            ),
            Media(
                id = 30,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 16",
                type = MediaType.MOVIE,
                categories = listOf("Action", "Horror"),
                yearOfRelease = LocalDate(1993, 8, 16),
                rating = 6.6,
            ),
            Media(
                id = 31,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 15",
                type = MediaType.TVSHOW,
                categories = listOf("Drama", "Mystery"),
                yearOfRelease = LocalDate(1992, 11, 28),
                rating = 7.8,
            ),
            Media(
                id = 32,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 17",
                type = MediaType.MOVIE,
                categories = listOf("Comedy", "Romance"),
                yearOfRelease = LocalDate(1991, 2, 10),
                rating = 7.0,
            ),
            Media(
                id = 33,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 16",
                type = MediaType.TVSHOW,
                categories = listOf("Action", "Adventure"),
                yearOfRelease = LocalDate(1990, 5, 22),
                rating = 7.4,
            ),
            Media(
                id = 34,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 18",
                type = MediaType.MOVIE,
                categories = listOf("Drama", "Thriller"),
                yearOfRelease = LocalDate(1989, 7, 13),
                rating = 7.2,
            ),
            Media(
                id = 35,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 17",
                type = MediaType.TVSHOW,
                categories = listOf("Comedy", "Fantasy"),
                yearOfRelease = LocalDate(1988, 10, 5),
                rating = 8.1,
            ),
            Media(
                id = 36,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 19",
                type = MediaType.MOVIE,
                categories = listOf("Action", "Horror"),
                yearOfRelease = LocalDate(1987, 12, 18),
                rating = 6.7,
            ),
            Media(
                id = 37,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 18",
                type = MediaType.TVSHOW,
                categories = listOf("Drama", "Mystery"),
                yearOfRelease = LocalDate(1986, 3, 9),
                rating = 7.6,
            ),
            Media(
                id = 38,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 20",
                type = MediaType.MOVIE,
                categories = listOf("Comedy", "Romance"),
                yearOfRelease = LocalDate(1985, 6, 21),
                rating = 7.1,
            ),
            Media(
                id = 39,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example TV Show 19",
                type = MediaType.TVSHOW,
                categories = listOf("Action", "Adventure"),
                yearOfRelease = LocalDate(1984, 8, 30),
                rating = 7.5,
            ),
            Media(
                id = 40,
                imageUri = "android.resource://com.paris_2.aflami.designsystem/drawable/anime_horizontal",
                title = "Example Movie 20",
                type = MediaType.MOVIE,
                categories = listOf("Drama", "Thriller"),
                yearOfRelease = LocalDate(1983, 11, 12),
                rating = 7.3,
            ),
        )
        val searchHistoryList = mutableListOf<SearchHistoryModel>(
            SearchHistoryModel(
                id = 1,
                searchTitle = "Example Movie 1",
            ),
            SearchHistoryModel(
                id = 2,
                searchTitle = "Example TV Show 1",
            ),
            SearchHistoryModel(
                id = 3,
                searchTitle = "Example Movie 2",
            ),
            SearchHistoryModel(
                id = 4,
                searchTitle = "Example TV Show 2",
            ),
            SearchHistoryModel(
                id = 5,
                searchTitle = "Example Movie 3",
            ),
            SearchHistoryModel(
                id = 6,
                searchTitle = "Example TV Show 3",
            ),
            SearchHistoryModel(
                id = 7,
                searchTitle = "Example Movie 4",
            ),
            SearchHistoryModel(
                id = 8,
                searchTitle = "Example TV Show 4",
            ),
            SearchHistoryModel(
                id = 9,
                searchTitle = "Example Movie 5",
            ),
            SearchHistoryModel(
                id = 10,
                searchTitle = "Example TV Show 5",
            ),
            SearchHistoryModel(
                id = 11,
                searchTitle = "Example Movie 6",
            ),
            SearchHistoryModel(
                id = 12,
                searchTitle = "Example TV Show 6",
            ),
            SearchHistoryModel(
                id = 13,
                searchTitle = "Example Movie 7",
            ),
            SearchHistoryModel(
                id = 14,
                searchTitle = "Example TV Show 7",
            ),
            SearchHistoryModel(
                id = 15,
                searchTitle = "Example Movie 8",
            ),
            SearchHistoryModel(
                id = 16,
                searchTitle = "Example TV Show 8",
            ),
            SearchHistoryModel(
                id = 17,
                searchTitle = "Example Movie 9",
            ),
            SearchHistoryModel(
                id = 18,
                searchTitle = "Example TV Show 9",
            ),
            SearchHistoryModel(
                id = 19,
                searchTitle = "Example Movie 10",
            ),
            SearchHistoryModel(
                id = 20,
                searchTitle = "Example TV Show 10",
            ),
            SearchHistoryModel(
                id = 21,
                searchTitle = "Example Movie 11",
            ),
            SearchHistoryModel(
                id = 22,
                searchTitle = "Example TV Show 11",
            ),
            SearchHistoryModel(
                id = 23,
                searchTitle = "Example Movie 12",
            ),
            SearchHistoryModel(
                id = 24,
                searchTitle = "Example TV Show 12",
            ),
            SearchHistoryModel(
                id = 25,
                searchTitle = "Example Movie 13",
            ),
        )
        val countryList = listOf(
            "United States",
            "Canada",
            "United Kingdom",
            "Australia",
            "India",
            "Japan",
            "South Korea",
            "France",
            "Germany",
            "Italy",
            "Spain",
            "Brazil",
            "Mexico",
            "Russia",
            "China"
        )
        val MoviesList = mediaList.filter { it.type == MediaType.MOVIE }
    }

}