object Modules {
    const val APP = ":app"
    const val DESIGN_SYSTEM = ":designsystem"
    const val LOGGER = ":logger"

    const val DOMAIN_USER = ":domain:user"
    const val DOMAIN_GUESS_GAME = ":domain:guessGame"
    const val DOMAIN_MEDIA = ":domain:media"
    const val DOMAIN_LISTS = ":domain:lists"

    const val REPOSITORY_MOVIE = ":repository:movie"
    const val REPOSITORY_TV_SHOW = ":repository:tvShows"
    const val REPOSITORY_LISTS = ":repository:lists"
    const val REPOSITORY_GUESS_GAME = ":repository:guessGame"
    const val REPOSITORY_MEDIA = ":repository:media"
    const val REPOSITORY_USER = ":repository:user"

    const val DATASOURCE_REMOTE_MOVIE = ":datasource:remote:movie"
    const val DATASOURCE_LOCAL_MOVIE = ":datasource:local:movie"
    const val DATASOURCE_REMOTE_TV_SHOW = ":datasource:remote:tvShow"
    const val DATASOURCE_LOCAL_TV_SHOW = ":datasource:local:tvShow"
    const val DATASOURCE_REMOTE_LISTS = ":datasource:remote:lists"
    const val DATASOURCE_LOCAL_LISTS = ":datasource:local:lists"
    const val DATASOURCE_LOCAL_GUESS_GAME = ":datasource:local:guessGame"
    const val DATASOURCE_REMOTE_CATEGORIES = ":datasource:remote:categories"
    const val DATASOURCE_LOCAL_CATEGORIES = ":datasource:local:categories"
    const val DATASOURCE_LOCAL_MEDIA = ":datasource:local:media"
    const val DATASOURCE_REMOTE_MEDIA = ":datasource:remote:media"
    const val DATASOURCE_LOCAL_USER = ":datasource:local:user"
    const val DATASOURCE_REMOTE_USER = ":datasource:remote:user"

    const val BOTTOM_NAV_BAR = ":feature:bottomNavBar"
    const val FEATURE_ONBOARDING_API = ":feature:onboarding:onboardingApi"
    const val FEATURE_ONBOARDING_UI = ":feature:onboarding:onboardingUi"
    const val FEATURE_AUTHENTICATION_API = ":feature:authentication:authenticationApi"
    const val FEATURE_AUTHENTICATION_UI = ":feature:authentication:authenticationUi"
    const val FEATURE_HOME_API = ":feature:home:homeApi"
    const val FEATURE_HOME_UI = ":feature:home:homeUi"
    const val FEATURE_SEARCH_API = ":feature:search:searchApi"
    const val FEATURE_SEARCH_UI = ":feature:search:searchUi"
    const val FEATURE_MEDIA_DETAILS_API = ":feature:mediaDetails:mediaDetailsApi"
    const val FEATURE_MEDIA_DETAILS_UI = ":feature:mediaDetails:mediaDetailsUi"
    const val FEATURE_GUESS_GAME_API = ":feature:guessGame:guessGameApi"
    const val FEATURE_GUESS_GAME_UI = ":feature:guessGame:guessGameUi"
    const val FEATURE_CATEGORIES_API = ":feature:categories:categoriesApi"
    const val FEATURE_CATEGORIES_UI = ":feature:categories:categoriesUi"
    const val FEATURE_LISTS_API = ":feature:lists:listsApi"
    const val FEATURE_LISTS_UI = ":feature:lists:listsUi"
    const val FEATURE_PROFILE_API = ":feature:profile:profileApi"
    const val FEATURE_PROFILE_UI = ":feature:profile:profileUi"

    const val SAFE_IMAGE_VIEWER = ":safeimageviewer"

}
