name: Android CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

  test-and-coverage:
    name: Run Unit Tests & Generate Coverage Report
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Generate coverage XML report
        run: ./gradlew koverXmlReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/reports/kover/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate coverage HTML report
        run: ./gradlew koverHtmlReport

      - name: Verify coverage
        run: ./gradlew koverVerify
