name: CD - Build & Distribute to Firebase App Distribution

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Give gradlew permission to execute
        run: chmod +x ./gradlew

      - name: Set up Firebase service credentials
        run: echo '${{ secrets.CREDENTIAL_FILE_CONTENT }}' > firebase-service-account.json

      - name: Build and distribute debug APK to Firebase App Distribution
        run: ./gradlew assembleDebug appDistributionUploadDebug
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_SERVICE_ACCOUNT_FILE: firebase-service-account.json