name: CD - Build & Distribute to Firebase App Distribution

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> local.properties

      - name: Restore keystore from Base64 secret
        run: |
          mkdir -p $GITHUB_WORKSPACE/appkey
          echo "$JKS_BASE64" | base64 --decode > $GITHUB_WORKSPACE/appkey/aflami-release-key.jks
        env:
          JKS_BASE64: ${{ secrets.JKS_BASE64 }}

      - name: Prepare signing env vars
        run: |
          echo "KEYSTORE_PATH=$GITHUB_WORKSPACE/appkey/aflami-release-key.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Check if keystore file exists
        run: |
          if [ -f "$GITHUB_WORKSPACE/appkey/aflami-release-key.jks" ]; then
            echo "✅ Keystore file restored successfully."
          else
            echo "❌ Keystore file is missing!"
            exit 1
          fi

      - name: Give gradlew permission to execute
        run: chmod +x ./gradlew

      - name: Build release singed APK
        run: ./gradlew app:assembleRelease

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: paris_squad_testers
          file: app/build/outputs/apk/release/app-release.apk
          releaseNotesFile: app/release-info.txt
          debug: false